name: Build and push Docker image to registry

on:
  push:
    branches:
      - 'main'

env:
  GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}
  GITEA_IMAGE_NAME: ${{ vars.IMAGE_HOSTNAME }}/${{ github.repository }}

jobs:
  build_and_push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ vars.PUSH_TO_GITEA != 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set short SHA
        id: short_sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_IMAGE_NAME }}:latest
            ${{ env.GHCR_IMAGE_NAME }}:${{ steps.short_sha.outputs.SHORT_SHA }}

  build_and_push_to_gitea:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ vars.PUSH_TO_GITEA == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set short SHA
        id: short_sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: TESTING
        run: |
          curl https://git.brandonb.ca

      - name: Log in to Gitea CR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.IMAGE_HOSTNAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITEA_IMAGE_NAME }}:latest
            ${{ env.GITEA_IMAGE_NAME }}:${{ steps.short_sha.outputs.SHORT_SHA }}
