name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint:nofix

      # - name: Run tests
      #   run: npm run test
